name: Release Shaarli Material

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+(-.*)?'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Build plugin
        run: |
          npm install
          npm run build

      - name: Package
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          zip -r shaarli-material.$tag.zip material
          tar -czvf shaarli-material.$tag.tar.gz material

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          gh release create "$tag" \
            --title="$tag" \
            --draft \
            shaarli-material.$tag.zip shaarli-material.$tag.tar.gz
